apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: nmap-api-svc
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: nmap-api
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nmap-api
  name: nmap-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nmap-api
  template:
    metadata:
      labels:
        app: nmap-api
    spec:
      containers:
      - image: drouleaufsa/nmap_api-python:1.0.0
        imagePullPolicy: Always
        name: nmap-api
        ports:
        - containerPort: 5000
